//
//  AlbumsViewController.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AlbumsViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: AlbumsInteractorProtocol)
    func set(router: AlbumsRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class AlbumsViewController: UIViewController, AlbumsViewControllerProtocol {

    // MARK: DI
    var interactor: AlbumsInteractorProtocol?
    var router: AlbumsRouterProtocol?

    func set(interactor: AlbumsInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: AlbumsRouterProtocol) {
        self.router = router
    }
    

    // MARK: Outlets

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Actions

}

// MARK: Methods
extension AlbumsViewController {

    func display(error: Error) {
        //TO DO: better error handling
    }
}
