////
//  AlbumsRouter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AlbumsRouterProtocol {
  func set(viewController: AlbumsViewControllerProtocol?)
  func route(to scene: AlbumsRouter.Scene)
}

class AlbumsRouter: NSObject, AlbumsRouterProtocol {

    //MARK: DI
    weak var viewController: AlbumsViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol

    func set(viewController: AlbumsViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol
    ) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: Routing logic
extension AlbumsRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: AlbumsRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

