////
//  AlbumsRouter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AlbumsRouterProtocol {
  func set(viewController: AlbumsViewControllerProtocol?)
  func route(to scene: AlbumsRouter.Scene)
}

class AlbumsRouter: NSObject, AlbumsRouterProtocol {

    //MARK: DI
    weak var viewController: AlbumsViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let photosStoryboard: Storyboard

    func set(viewController: AlbumsViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        photosStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.photosStoryboard = photosStoryboard
    }
}

// MARK: Routing logic
extension AlbumsRouter {

    enum Scene {
        case photos(albumId: Int)
    }

    func route(to scene: AlbumsRouter.Scene) {
        switch scene {
        case .photos(let albumId):
            guard let vc = photosStoryboard.viewController(identifier: PhotosStoryboardId.photos) as? PhotosViewController else { return }
            vc.set(albumId: albumId)
            viewController?.show(vc, sender: nil)
        }
    }
}

