//
//  AlbumsPresenter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AlbumsPresenterProtocol {
    func set(viewController: AlbumsViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
}

class AlbumsPresenter: AlbumsPresenterProtocol {

    // MARK: DI
    weak var viewController: AlbumsViewControllerProtocol?

    func set(viewController: AlbumsViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  AlbumsPresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }
}
