////
//  PhotoDetailRouter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PhotoDetailRouterProtocol {
  func set(viewController: PhotoDetailViewControllerProtocol?)
  func route(to scene: PhotoDetailRouter.Scene)
}

class PhotoDetailRouter: NSObject, PhotoDetailRouterProtocol {

    //MARK: DI
    weak var viewController: PhotoDetailViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol


    func set(viewController: PhotoDetailViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol
    ) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: Routing logic
extension PhotoDetailRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: PhotoDetailRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

