//
//  PhotoDetailViewController.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Kingfisher

protocol PhotoDetailViewControllerProtocol: UIViewControllerRouting {
    func set(interactor: PhotoDetailInteractorProtocol)
    func set(router: PhotoDetailRouterProtocol)
    func set(photo: Photo)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class PhotoDetailViewController: UIViewController, PhotoDetailViewControllerProtocol {

    // MARK: Outlets
    @IBOutlet weak var imageView: UIImageView!

    // MARK: DI
    var interactor: PhotoDetailInteractorProtocol?
    var router: PhotoDetailRouterProtocol?

    func set(interactor: PhotoDetailInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: PhotoDetailRouterProtocol) {
        self.router = router
    }

    func set(photo: Photo) {
        interactor?.set(photo: photo)
    }


    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        guard let imageUrl = interactor?.photo?.url,
        let url = URL(string: imageUrl) else { return }
        imageView.kf.setImage(with: url)
    }

    // MARK: Actions

}

// MARK: Methods
extension PhotoDetailViewController {

    func display(error: Error) {
        //TO DO: better error handling
    }
}
