//
//  PhotoDetailInteractor.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PhotoDetailInteractorProtocol {
    func set(photo: Photo)
    var photo: Photo? { get }
}

class PhotoDetailInteractor: PhotoDetailInteractorProtocol {
    var photo: Photo?

    // MARK: DI
    var presenter: PhotoDetailPresenterProtocol

    init(presenter: PhotoDetailPresenterProtocol) {
        self.presenter = presenter
    }

    func set(photo: Photo) {
        self.photo = photo
    }
}
