//
//  PhotosPresenter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PhotosPresenterProtocol {
    func set(viewController: PhotosViewControllerProtocol?)
    func presentPhotos(photos: [Photo])
}

class PhotosPresenter: PhotosPresenterProtocol {

    // MARK: DI
    weak var viewController: PhotosViewControllerProtocol?

    func set(viewController: PhotosViewControllerProtocol?) {
        self.viewController = viewController
    }

    // MARK: Methods
    func presentPhotos(photos: [Photo]) {
        viewController?.displayPhotos(photos: photos)
    }
}
