//
//  PhotosViewController.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PhotosViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: PhotosInteractorProtocol)
    func set(router: PhotosRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class PhotosViewController: UIViewController, PhotosViewControllerProtocol {

    // MARK: DI
    var interactor: PhotosInteractorProtocol?
    var router: PhotosRouterProtocol?

    func set(interactor: PhotosInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: PhotosRouterProtocol) {
        self.router = router
    }
    

    // MARK: Outlets

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Actions

}

// MARK: Methods
extension PhotosViewController {

    func display(error: Error) {
        //TO DO: better error handling
        
    }
}
