////
//  PhotosRouter.swift
//  MediaMonks
//
//  Created by Karim Cordilia on 01/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PhotosRouterProtocol {
  func set(viewController: PhotosViewControllerProtocol?)
  func route(to scene: PhotosRouter.Scene)
}

class PhotosRouter: NSObject, PhotosRouterProtocol {

    //MARK: DI
    weak var viewController: PhotosViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol

    func set(viewController: PhotosViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol
    ) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: Routing logic
extension PhotosRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: PhotosRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

